// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppConfigSnapshot {
    "adb_path": string;
    "fastboot_path": string;
    "scrcpy_path": string;
    "setup_completed": boolean;
    "theme": string;
    "binary_versions": { [_ in string]?: string };
    "device_nicknames": { [_ in string]?: string };
    "logcat_buffer_limit": number;
    "scrcpy_options": ScrcpyOptions;
    "scrcpy_presets": ScrcpyPreset[];
    "default_terminal_mode": string;
    "auto_refresh_devices": boolean;
    "device_refresh_seconds": number;
    "audit_enabled": boolean;

    /** Creates a new AppConfigSnapshot instance. */
    constructor($$source: Partial<AppConfigSnapshot> = {}) {
        if (!("adb_path" in $$source)) {
            this["adb_path"] = "";
        }
        if (!("fastboot_path" in $$source)) {
            this["fastboot_path"] = "";
        }
        if (!("scrcpy_path" in $$source)) {
            this["scrcpy_path"] = "";
        }
        if (!("setup_completed" in $$source)) {
            this["setup_completed"] = false;
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("binary_versions" in $$source)) {
            this["binary_versions"] = {};
        }
        if (!("device_nicknames" in $$source)) {
            this["device_nicknames"] = {};
        }
        if (!("logcat_buffer_limit" in $$source)) {
            this["logcat_buffer_limit"] = 0;
        }
        if (!("scrcpy_options" in $$source)) {
            this["scrcpy_options"] = (new ScrcpyOptions());
        }
        if (!("scrcpy_presets" in $$source)) {
            this["scrcpy_presets"] = [];
        }
        if (!("default_terminal_mode" in $$source)) {
            this["default_terminal_mode"] = "";
        }
        if (!("auto_refresh_devices" in $$source)) {
            this["auto_refresh_devices"] = false;
        }
        if (!("device_refresh_seconds" in $$source)) {
            this["device_refresh_seconds"] = 0;
        }
        if (!("audit_enabled" in $$source)) {
            this["audit_enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfigSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfigSnapshot {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("binary_versions" in $$parsedSource) {
            $$parsedSource["binary_versions"] = $$createField5_0($$parsedSource["binary_versions"]);
        }
        if ("device_nicknames" in $$parsedSource) {
            $$parsedSource["device_nicknames"] = $$createField6_0($$parsedSource["device_nicknames"]);
        }
        if ("scrcpy_options" in $$parsedSource) {
            $$parsedSource["scrcpy_options"] = $$createField8_0($$parsedSource["scrcpy_options"]);
        }
        if ("scrcpy_presets" in $$parsedSource) {
            $$parsedSource["scrcpy_presets"] = $$createField9_0($$parsedSource["scrcpy_presets"]);
        }
        return new AppConfigSnapshot($$parsedSource as Partial<AppConfigSnapshot>);
    }
}

/**
 * BinaryInfo describes a discovered binary candidate.
 */
export class BinaryInfo {
    "name": string;
    "path": string;
    "source": string;
    "status": BinaryStatus;
    "version"?: string;
    "reason"?: string;

    /** Creates a new BinaryInfo instance. */
    constructor($$source: Partial<BinaryInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = BinaryStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BinaryInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BinaryInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BinaryInfo($$parsedSource as Partial<BinaryInfo>);
    }
}

/**
 * BinaryStatus describes the readiness state of an external binary.
 */
export enum BinaryStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BinaryMissing = "missing",
    BinaryInvalid = "invalid_path",
    BinaryReady = "ready",
};

export class PreferencesPayload {
    "theme": string;
    "device_nicknames": { [_ in string]?: string };
    "logcat_buffer_limit": number;
    "scrcpy_presets": ScrcpyPreset[];
    "default_terminal_mode": string;
    "auto_refresh_devices": boolean;
    "device_refresh_seconds": number;
    "audit_enabled"?: boolean | null;

    /** Creates a new PreferencesPayload instance. */
    constructor($$source: Partial<PreferencesPayload> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("device_nicknames" in $$source)) {
            this["device_nicknames"] = {};
        }
        if (!("logcat_buffer_limit" in $$source)) {
            this["logcat_buffer_limit"] = 0;
        }
        if (!("scrcpy_presets" in $$source)) {
            this["scrcpy_presets"] = [];
        }
        if (!("default_terminal_mode" in $$source)) {
            this["default_terminal_mode"] = "";
        }
        if (!("auto_refresh_devices" in $$source)) {
            this["auto_refresh_devices"] = false;
        }
        if (!("device_refresh_seconds" in $$source)) {
            this["device_refresh_seconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreferencesPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): PreferencesPayload {
        const $$createField1_0 = $$createType0;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("device_nicknames" in $$parsedSource) {
            $$parsedSource["device_nicknames"] = $$createField1_0($$parsedSource["device_nicknames"]);
        }
        if ("scrcpy_presets" in $$parsedSource) {
            $$parsedSource["scrcpy_presets"] = $$createField3_0($$parsedSource["scrcpy_presets"]);
        }
        return new PreferencesPayload($$parsedSource as Partial<PreferencesPayload>);
    }
}

export class RuntimeDiagnostics {
    "os": string;
    "arch": string;
    "data_dir": string;
    "config_path": string;
    "managed_binary_dir": string;
    "setup_completed": boolean;
    "theme": string;
    "binary_versions": { [_ in string]?: string };
    "capabilities": { [_ in string]?: boolean };

    /** Creates a new RuntimeDiagnostics instance. */
    constructor($$source: Partial<RuntimeDiagnostics> = {}) {
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }
        if (!("data_dir" in $$source)) {
            this["data_dir"] = "";
        }
        if (!("config_path" in $$source)) {
            this["config_path"] = "";
        }
        if (!("managed_binary_dir" in $$source)) {
            this["managed_binary_dir"] = "";
        }
        if (!("setup_completed" in $$source)) {
            this["setup_completed"] = false;
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("binary_versions" in $$source)) {
            this["binary_versions"] = {};
        }
        if (!("capabilities" in $$source)) {
            this["capabilities"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeDiagnostics instance from a string or object.
     */
    static createFrom($$source: any = {}): RuntimeDiagnostics {
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("binary_versions" in $$parsedSource) {
            $$parsedSource["binary_versions"] = $$createField7_0($$parsedSource["binary_versions"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField8_0($$parsedSource["capabilities"]);
        }
        return new RuntimeDiagnostics($$parsedSource as Partial<RuntimeDiagnostics>);
    }
}

export class ScrcpyOptions {
    "max_size": number;
    "bit_rate": number;
    "max_fps": number;
    "audio_bit_rate": number;
    "audio_codec": string;
    "video_codec": string;
    "show_touches": boolean;
    "no_audio": boolean;
    "no_control": boolean;
    "stay_awake": boolean;
    "turn_screen_off": boolean;
    "power_off_on_close": boolean;
    "fullscreen": boolean;
    "always_on_top": boolean;
    "disable_screensaver": boolean;
    "rotation": number;
    "display_id": number;
    "time_limit": number;

    /** Creates a new ScrcpyOptions instance. */
    constructor($$source: Partial<ScrcpyOptions> = {}) {
        if (!("max_size" in $$source)) {
            this["max_size"] = 0;
        }
        if (!("bit_rate" in $$source)) {
            this["bit_rate"] = 0;
        }
        if (!("max_fps" in $$source)) {
            this["max_fps"] = 0;
        }
        if (!("audio_bit_rate" in $$source)) {
            this["audio_bit_rate"] = 0;
        }
        if (!("audio_codec" in $$source)) {
            this["audio_codec"] = "";
        }
        if (!("video_codec" in $$source)) {
            this["video_codec"] = "";
        }
        if (!("show_touches" in $$source)) {
            this["show_touches"] = false;
        }
        if (!("no_audio" in $$source)) {
            this["no_audio"] = false;
        }
        if (!("no_control" in $$source)) {
            this["no_control"] = false;
        }
        if (!("stay_awake" in $$source)) {
            this["stay_awake"] = false;
        }
        if (!("turn_screen_off" in $$source)) {
            this["turn_screen_off"] = false;
        }
        if (!("power_off_on_close" in $$source)) {
            this["power_off_on_close"] = false;
        }
        if (!("fullscreen" in $$source)) {
            this["fullscreen"] = false;
        }
        if (!("always_on_top" in $$source)) {
            this["always_on_top"] = false;
        }
        if (!("disable_screensaver" in $$source)) {
            this["disable_screensaver"] = false;
        }
        if (!("rotation" in $$source)) {
            this["rotation"] = 0;
        }
        if (!("display_id" in $$source)) {
            this["display_id"] = 0;
        }
        if (!("time_limit" in $$source)) {
            this["time_limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScrcpyOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ScrcpyOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScrcpyOptions($$parsedSource as Partial<ScrcpyOptions>);
    }
}

export class ScrcpyPreset {
    "name": string;
    "options": ScrcpyOptions;

    /** Creates a new ScrcpyPreset instance. */
    constructor($$source: Partial<ScrcpyPreset> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("options" in $$source)) {
            this["options"] = (new ScrcpyOptions());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScrcpyPreset instance from a string or object.
     */
    static createFrom($$source: any = {}): ScrcpyPreset {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField1_0($$parsedSource["options"]);
        }
        return new ScrcpyPreset($$parsedSource as Partial<ScrcpyPreset>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = ScrcpyOptions.createFrom;
const $$createType2 = ScrcpyPreset.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
