// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ProgressEvent {
    "name": string;
    "percent": number;
    "bytesReceived": number;
    "bytesTotal": number;
    "status": string;

    /** Creates a new ProgressEvent instance. */
    constructor($$source: Partial<ProgressEvent> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }
        if (!("bytesReceived" in $$source)) {
            this["bytesReceived"] = 0;
        }
        if (!("bytesTotal" in $$source)) {
            this["bytesTotal"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProgressEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ProgressEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProgressEvent($$parsedSource as Partial<ProgressEvent>);
    }
}
