// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Entry {
    "name": string;
    "path": string;
    "type": string;
    "size": number;
    "sizeHuman": string;
    "permissions": string;
    "modifiedAt": string;
    "isHidden": boolean;
}

export interface StorageInfo {
    "mountPoint": string;
    "totalBytes": number;
    "usedBytes": number;
    "freeBytes": number;
    "usedPct": number;
}

export interface TransferProgress {
    "fileName": string;
    "direction": string;
    "percent": number;
}
