// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Entry {
    "name": string;
    "path": string;
    "type": string;
    "size": number;
    "sizeHuman": string;
    "permissions": string;
    "modifiedAt": string;
    "isHidden": boolean;

    /** Creates a new Entry instance. */
    constructor($$source: Partial<Entry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("sizeHuman" in $$source)) {
            this["sizeHuman"] = "";
        }
        if (!("permissions" in $$source)) {
            this["permissions"] = "";
        }
        if (!("modifiedAt" in $$source)) {
            this["modifiedAt"] = "";
        }
        if (!("isHidden" in $$source)) {
            this["isHidden"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     */
    static createFrom($$source: any = {}): Entry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry($$parsedSource as Partial<Entry>);
    }
}

export class StorageInfo {
    "mountPoint": string;
    "totalBytes": number;
    "usedBytes": number;
    "freeBytes": number;
    "usedPct": number;

    /** Creates a new StorageInfo instance. */
    constructor($$source: Partial<StorageInfo> = {}) {
        if (!("mountPoint" in $$source)) {
            this["mountPoint"] = "";
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("usedBytes" in $$source)) {
            this["usedBytes"] = 0;
        }
        if (!("freeBytes" in $$source)) {
            this["freeBytes"] = 0;
        }
        if (!("usedPct" in $$source)) {
            this["usedPct"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StorageInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): StorageInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StorageInfo($$parsedSource as Partial<StorageInfo>);
    }
}

export class TransferProgress {
    "fileName": string;
    "direction": string;
    "percent": number;

    /** Creates a new TransferProgress instance. */
    constructor($$source: Partial<TransferProgress> = {}) {
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransferProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): TransferProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransferProgress($$parsedSource as Partial<TransferProgress>);
    }
}
