// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PlatformToolsSelection {
    "directory": string;
    "adbPath": string;
    "fastbootPath": string;

    /** Creates a new PlatformToolsSelection instance. */
    constructor($$source: Partial<PlatformToolsSelection> = {}) {
        if (!("directory" in $$source)) {
            this["directory"] = "";
        }
        if (!("adbPath" in $$source)) {
            this["adbPath"] = "";
        }
        if (!("fastbootPath" in $$source)) {
            this["fastbootPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlatformToolsSelection instance from a string or object.
     */
    static createFrom($$source: any = {}): PlatformToolsSelection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlatformToolsSelection($$parsedSource as Partial<PlatformToolsSelection>);
    }
}

export class ScrcpyDirectorySelection {
    "directory": string;
    "scrcpyPath": string;

    /** Creates a new ScrcpyDirectorySelection instance. */
    constructor($$source: Partial<ScrcpyDirectorySelection> = {}) {
        if (!("directory" in $$source)) {
            this["directory"] = "";
        }
        if (!("scrcpyPath" in $$source)) {
            this["scrcpyPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScrcpyDirectorySelection instance from a string or object.
     */
    static createFrom($$source: any = {}): ScrcpyDirectorySelection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScrcpyDirectorySelection($$parsedSource as Partial<ScrcpyDirectorySelection>);
    }
}
