// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Entry {
    "id": number;
    "timestamp": string;
    "level": LogLevel;
    "operation": string;
    "message": string;
    "details"?: string;
    "duration"?: string;
    "success": boolean;

    /** Creates a new Entry instance. */
    constructor($$source: Partial<Entry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("level" in $$source)) {
            this["level"] = LogLevel.$zero;
        }
        if (!("operation" in $$source)) {
            this["operation"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     */
    static createFrom($$source: any = {}): Entry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry($$parsedSource as Partial<Entry>);
    }
}

export enum LogLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LogLevelInfo = "info",
    LogLevelWarning = "warning",
    LogLevelError = "error",
    LogLevelDebug = "debug",
    LogLevelSuccess = "success",
};
