// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CodecSupport {
    "codec": string;
    "encoderName": string;
    "hardware": boolean;
    "vendor": boolean;
    "softwareOnly": boolean;
    "recommended": boolean;
    "aliasOf": string;

    /** Creates a new CodecSupport instance. */
    constructor($$source: Partial<CodecSupport> = {}) {
        if (!("codec" in $$source)) {
            this["codec"] = "";
        }
        if (!("encoderName" in $$source)) {
            this["encoderName"] = "";
        }
        if (!("hardware" in $$source)) {
            this["hardware"] = false;
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = false;
        }
        if (!("softwareOnly" in $$source)) {
            this["softwareOnly"] = false;
        }
        if (!("recommended" in $$source)) {
            this["recommended"] = false;
        }
        if (!("aliasOf" in $$source)) {
            this["aliasOf"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodecSupport instance from a string or object.
     */
    static createFrom($$source: any = {}): CodecSupport {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodecSupport($$parsedSource as Partial<CodecSupport>);
    }
}

export class EncoderSupport {
    "serial": string;
    "videoCodecs": CodecSupport[];
    "audioCodecs": CodecSupport[];

    /** Creates a new EncoderSupport instance. */
    constructor($$source: Partial<EncoderSupport> = {}) {
        if (!("serial" in $$source)) {
            this["serial"] = "";
        }
        if (!("videoCodecs" in $$source)) {
            this["videoCodecs"] = [];
        }
        if (!("audioCodecs" in $$source)) {
            this["audioCodecs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EncoderSupport instance from a string or object.
     */
    static createFrom($$source: any = {}): EncoderSupport {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("videoCodecs" in $$parsedSource) {
            $$parsedSource["videoCodecs"] = $$createField1_0($$parsedSource["videoCodecs"]);
        }
        if ("audioCodecs" in $$parsedSource) {
            $$parsedSource["audioCodecs"] = $$createField2_0($$parsedSource["audioCodecs"]);
        }
        return new EncoderSupport($$parsedSource as Partial<EncoderSupport>);
    }
}

export class Options {
    "max_size": number;
    "bit_rate": number;
    "max_fps": number;
    "audio_bit_rate": number;
    "audio_codec": string;
    "video_codec": string;
    "show_touches": boolean;
    "no_audio": boolean;
    "no_control": boolean;
    "stay_awake": boolean;
    "turn_screen_off": boolean;
    "power_off_on_close": boolean;
    "fullscreen": boolean;
    "always_on_top": boolean;
    "disable_screensaver": boolean;
    "rotation": number;
    "display_id": number;
    "time_limit": number;

    /** Creates a new Options instance. */
    constructor($$source: Partial<Options> = {}) {
        if (!("max_size" in $$source)) {
            this["max_size"] = 0;
        }
        if (!("bit_rate" in $$source)) {
            this["bit_rate"] = 0;
        }
        if (!("max_fps" in $$source)) {
            this["max_fps"] = 0;
        }
        if (!("audio_bit_rate" in $$source)) {
            this["audio_bit_rate"] = 0;
        }
        if (!("audio_codec" in $$source)) {
            this["audio_codec"] = "";
        }
        if (!("video_codec" in $$source)) {
            this["video_codec"] = "";
        }
        if (!("show_touches" in $$source)) {
            this["show_touches"] = false;
        }
        if (!("no_audio" in $$source)) {
            this["no_audio"] = false;
        }
        if (!("no_control" in $$source)) {
            this["no_control"] = false;
        }
        if (!("stay_awake" in $$source)) {
            this["stay_awake"] = false;
        }
        if (!("turn_screen_off" in $$source)) {
            this["turn_screen_off"] = false;
        }
        if (!("power_off_on_close" in $$source)) {
            this["power_off_on_close"] = false;
        }
        if (!("fullscreen" in $$source)) {
            this["fullscreen"] = false;
        }
        if (!("always_on_top" in $$source)) {
            this["always_on_top"] = false;
        }
        if (!("disable_screensaver" in $$source)) {
            this["disable_screensaver"] = false;
        }
        if (!("rotation" in $$source)) {
            this["rotation"] = 0;
        }
        if (!("display_id" in $$source)) {
            this["display_id"] = 0;
        }
        if (!("time_limit" in $$source)) {
            this["time_limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Options instance from a string or object.
     */
    static createFrom($$source: any = {}): Options {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Options($$parsedSource as Partial<Options>);
    }
}

export class Session {
    "id": string;
    "serial": string;
    "status": SessionStatus;
    "pid": number;
    "startedAt": number;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("serial" in $$source)) {
            this["serial"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = SessionStatus.$zero;
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session($$parsedSource as Partial<Session>);
    }
}

export class SessionEvent {
    "sessionId": string;
    "serial": string;
    "status": SessionStatus;
    "pid"?: number;
    "message"?: string;

    /** Creates a new SessionEvent instance. */
    constructor($$source: Partial<SessionEvent> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("serial" in $$source)) {
            this["serial"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = SessionStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionEvent($$parsedSource as Partial<SessionEvent>);
    }
}

export enum SessionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusStarting = "starting",
    StatusRunning = "running",
    StatusStopping = "stopping",
    StatusStopped = "stopped",
    StatusError = "error",
};

// Private type creation functions
const $$createType0 = CodecSupport.createFrom;
const $$createType1 = $Create.Array($$createType0);
