// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Info {
    "serial": string;
    "state": State;
    "mode": Mode;
    "product"?: string;
    "model"?: string;
    "device"?: string;
    "brand"?: string;
    "codename"?: string;
    "manufacturer"?: string;
    "androidVersion"?: string;
    "sdkVersion"?: string;
    "buildId"?: string;
    "securityPatch"?: string;
    "abis"?: string;
    "transportId"?: string;
    "connectionLabel"?: string;
    "ipAddress"?: string;
    "rootStatus"?: string;
    "batteryLevel"?: string;
    "storageInfo"?: string;
    "ramTotal"?: string;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("serial" in $$source)) {
            this["serial"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = State.$zero;
        }
        if (!("mode" in $$source)) {
            this["mode"] = Mode.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info($$parsedSource as Partial<Info>);
    }
}

export enum Mode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ModeADB = "adb",
    ModeFastboot = "fastboot",
    ModeUnknown = "unknown",
};

export class PerformanceSnapshot {
    "serial": string;
    "cpuUsage": number;
    "ramUsage": number;
    "ramUsedBytes"?: number;
    "ramTotalBytes"?: number;
    "networkRxBytes"?: number;
    "networkTxBytes"?: number;
    "networkRxSec": number;
    "networkTxSec": number;
    "batteryLevel"?: number;
    "batteryTemperatureC"?: number;
    "storageUsedBytes"?: number;
    "storageTotalBytes"?: number;
    "uptimeSeconds"?: number;

    /** Creates a new PerformanceSnapshot instance. */
    constructor($$source: Partial<PerformanceSnapshot> = {}) {
        if (!("serial" in $$source)) {
            this["serial"] = "";
        }
        if (!("cpuUsage" in $$source)) {
            this["cpuUsage"] = 0;
        }
        if (!("ramUsage" in $$source)) {
            this["ramUsage"] = 0;
        }
        if (!("networkRxSec" in $$source)) {
            this["networkRxSec"] = 0;
        }
        if (!("networkTxSec" in $$source)) {
            this["networkTxSec"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PerformanceSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): PerformanceSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PerformanceSnapshot($$parsedSource as Partial<PerformanceSnapshot>);
    }
}

export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateReady = "device",
    StateOffline = "offline",
    StateUnauthorized = "unauthorized",
    StateRecovery = "recovery",
    StateSideload = "sideload",
    StateFastboot = "fastboot",
    StateUnknown = "unknown",
};

export class Summary {
    "serial": string;
    "state": State;
    "mode": Mode;
    "product"?: string;
    "model"?: string;
    "device"?: string;
    "transportId"?: string;

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("serial" in $$source)) {
            this["serial"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = State.$zero;
        }
        if (!("mode" in $$source)) {
            this["mode"] = Mode.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Summary($$parsedSource as Partial<Summary>);
    }
}
