// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as audit$0 from "./internal/audit/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as binary$0 from "./internal/binary/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "./internal/core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as device$0 from "./internal/device/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dialog$0 from "./internal/dialog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as file$0 from "./internal/file/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as flasher$0 from "./internal/flasher/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as packagemgr$0 from "./internal/package_mgr/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scrcpy$0 from "./internal/scrcpy/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as shell$0 from "./internal/shell/models.js";

export function CancelFileTransfer(): $CancellablePromise<void> {
    return $Call.ByID(3945828302);
}

export function ClearAuditLogs(): $CancellablePromise<void> {
    return $Call.ByID(376998614);
}

export function ClearCustomBinary(name: string): $CancellablePromise<void> {
    return $Call.ByID(31483808, name);
}

export function ClearDeviceNickname(serial: string): $CancellablePromise<void> {
    return $Call.ByID(5551320, serial);
}

export function ClearPackageData(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(601431250, packageName);
}

export function CloseTerminal(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2702963191, sessionID);
}

export function CompleteSetup(): $CancellablePromise<binary$0.SetupState | null> {
    return $Call.ByID(507086583);
}

export function ConnectWireless(address: string): $CancellablePromise<string> {
    return $Call.ByID(3954743789, address);
}

export function CreateDirectory(remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(148843624, remotePath);
}

export function DeleteFile(remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(2962294020, remotePath);
}

export function DeleteMultipleFiles(remotePaths: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(1674076513, remotePaths);
}

export function DisableMultiplePackages(packageNames: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(3372204106, packageNames);
}

export function DisablePackage(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(832153241, packageName);
}

export function DisconnectWireless(address: string): $CancellablePromise<string> {
    return $Call.ByID(3633612175, address);
}

export function DownloadPlatformTools(): $CancellablePromise<void> {
    return $Call.ByID(3062366105);
}

export function DownloadScrcpy(): $CancellablePromise<void> {
    return $Call.ByID(155176791);
}

export function EnableMultiplePackages(packageNames: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(2641208955, packageNames);
}

export function EnablePackage(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(3660890646, packageName);
}

export function EnableWirelessTCPIP(port: string, serial: string): $CancellablePromise<string> {
    return $Call.ByID(2088967908, port, serial);
}

export function ExportAuditLogs(path: string): $CancellablePromise<void> {
    return $Call.ByID(422103809, path);
}

/**
 * FastbootContinue boots a device out of fastboot/bootloader without a
 * physical Start/Power press (WOF - Wake on Fastboot).
 */
export function FastbootContinue(serial: string): $CancellablePromise<string> {
    return $Call.ByID(3631691234, serial);
}

export function FlashPartition(serial: string, partition: string, filePath: string): $CancellablePromise<string> {
    return $Call.ByID(4135109309, serial, partition, filePath);
}

export function FlashRomFolder(serial: string, folderPath: string, plan: flasher$0.Plan): $CancellablePromise<string> {
    return $Call.ByID(1826896165, serial, folderPath, plan);
}

export function ForceStopPackage(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(3041461116, packageName);
}

export function GetActiveScrcpySession(): $CancellablePromise<scrcpy$0.Session | null> {
    return $Call.ByID(498405169);
}

export function GetActiveSerial(): $CancellablePromise<string> {
    return $Call.ByID(4252605701);
}

export function GetActiveSlot(serial: string): $CancellablePromise<string> {
    return $Call.ByID(1760093333, serial);
}

export function GetAppConfig(): $CancellablePromise<core$0.AppConfigSnapshot> {
    return $Call.ByID(2006534548);
}

export function GetAuditLogs(limit: number): $CancellablePromise<audit$0.Entry[] | null> {
    return $Call.ByID(3554903517, limit);
}

export function GetBinaryStatus(): $CancellablePromise<binary$0.BinarySetupResult | null> {
    return $Call.ByID(3402209708);
}

export function GetCapabilities(): $CancellablePromise<{ [_ in string]?: boolean } | null> {
    return $Call.ByID(1046771829);
}

export function GetDeviceInfo(serial: string): $CancellablePromise<device$0.Info | null> {
    return $Call.ByID(3517594213, serial);
}

export function GetDeviceMode(serial: string): $CancellablePromise<device$0.Mode> {
    return $Call.ByID(2967333234, serial);
}

export function GetDeviceNicknames(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(3996901626);
}

export function GetDevices(): $CancellablePromise<device$0.Summary[] | null> {
    return $Call.ByID(2647233474);
}

export function GetDirectorySize(remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(2642196295, remotePath);
}

export function GetFastbootDevices(): $CancellablePromise<flasher$0.FastbootDeviceInfo[] | null> {
    return $Call.ByID(253529860);
}

export function GetManagedBinaryDir(): $CancellablePromise<string> {
    return $Call.ByID(3178982088);
}

export function GetPackageDetails(packageName: string): $CancellablePromise<packagemgr$0.Details> {
    return $Call.ByID(2013558629, packageName);
}

export function GetPerformanceSnapshot(serial: string): $CancellablePromise<device$0.PerformanceSnapshot> {
    return $Call.ByID(766417411, serial);
}

export function GetRuntimeDiagnostics(): $CancellablePromise<core$0.RuntimeDiagnostics> {
    return $Call.ByID(1478575635);
}

export function GetScrcpyClipboard(serial: string): $CancellablePromise<string> {
    return $Call.ByID(848041049, serial);
}

export function GetScrcpyEncoderSupport(serial: string): $CancellablePromise<scrcpy$0.EncoderSupport | null> {
    return $Call.ByID(3583182306, serial);
}

export function GetSetupState(): $CancellablePromise<binary$0.SetupState | null> {
    return $Call.ByID(3401338661);
}

/**
 * GetStayAwakeWhileCharging reports the current "Stay awake" setting state.
 */
export function GetStayAwakeWhileCharging(serial: string): $CancellablePromise<boolean> {
    return $Call.ByID(3708240313, serial);
}

export function GetStorageInfo(): $CancellablePromise<file$0.StorageInfo> {
    return $Call.ByID(3330596760);
}

export function ImportAuditLogs(path: string): $CancellablePromise<number> {
    return $Call.ByID(3364801048, path);
}

export function InstallPackage(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(611762984, filePath);
}

export function IsUserspaceFastboot(serial: string): $CancellablePromise<boolean> {
    return $Call.ByID(3160317206, serial);
}

export function LaunchPackage(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(3433551198, packageName);
}

export function ListFiles(remotePath: string, showHidden: boolean): $CancellablePromise<file$0.Entry[] | null> {
    return $Call.ByID(3557170708, remotePath, showHidden);
}

export function ListManagedBinaries(): $CancellablePromise<string[] | null> {
    return $Call.ByID(4113676651);
}

export function ListPackages(filterType: string): $CancellablePromise<packagemgr$0.Info[] | null> {
    return $Call.ByID(1422337916, filterType);
}

export function PullFile(remotePath: string, localPath: string): $CancellablePromise<string> {
    return $Call.ByID(3586487168, remotePath, localPath);
}

export function PullMultipleFiles(remotePaths: string[] | null, localDirectory: string): $CancellablePromise<string> {
    return $Call.ByID(2223369877, remotePaths, localDirectory);
}

export function PullPackageApk(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(336426316, packageName);
}

export function PushFile(localPath: string, remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(2369675219, localPath, remotePath);
}

export function PushMultipleFiles(localPaths: string[] | null, remoteDirectory: string): $CancellablePromise<string> {
    return $Call.ByID(1625742572, localPaths, remoteDirectory);
}

export function PushScrcpyClipboard(serial: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(4115231475, serial, text);
}

export function RebootDevice(serial: string, mode: string): $CancellablePromise<string> {
    return $Call.ByID(2977535306, serial, mode);
}

export function RenameFile(oldRemotePath: string, newRemotePath: string): $CancellablePromise<string> {
    return $Call.ByID(1151698069, oldRemotePath, newRemotePath);
}

export function RetryBinaryDetection(): $CancellablePromise<binary$0.BinarySetupResult | null> {
    return $Call.ByID(1429285115);
}

export function RunCustomFastbootCommand(serial: string, args: string): $CancellablePromise<string> {
    return $Call.ByID(1316204092, serial, args);
}

export function SaveLogcatToFile(content: string, defaultFilename: string): $CancellablePromise<void> {
    return $Call.ByID(1604176709, content, defaultFilename);
}

export function ScanRomFolder(folderPath: string): $CancellablePromise<flasher$0.Plan | null> {
    return $Call.ByID(2865191018, folderPath);
}

export function SelectApkFile(): $CancellablePromise<string> {
    return $Call.ByID(1369536299);
}

export function SelectBinaryFile(name: string): $CancellablePromise<string> {
    return $Call.ByID(464792586, name);
}

export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1735672136);
}

export function SelectFile(): $CancellablePromise<string> {
    return $Call.ByID(2427571203);
}

export function SelectFlashImageFile(): $CancellablePromise<string> {
    return $Call.ByID(2558180776);
}

export function SelectMultipleFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1093120572);
}

export function SelectPlatformToolsDirectory(): $CancellablePromise<dialog$0.PlatformToolsSelection | null> {
    return $Call.ByID(2864029600);
}

export function SelectSavePath(defaultFilename: string): $CancellablePromise<string> {
    return $Call.ByID(1300572447, defaultFilename);
}

export function SelectSideloadFile(): $CancellablePromise<string> {
    return $Call.ByID(2360278840);
}

export function SendTerminalInput(sessionID: string, input: string): $CancellablePromise<void> {
    return $Call.ByID(180551177, sessionID, input);
}

export function SetActiveSerial(serial: string): $CancellablePromise<void> {
    return $Call.ByID(2810398185, serial);
}

export function SetActiveSlot(serial: string, slot: string): $CancellablePromise<string> {
    return $Call.ByID(3663736097, serial, slot);
}

export function SetCustomBinary(name: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(2028430557, name, path);
}

export function SetDeviceNickname(serial: string, nickname: string): $CancellablePromise<void> {
    return $Call.ByID(1412312329, serial, nickname);
}

/**
 * SetStayAwakeWhileCharging toggles the "Stay awake" developer option so the
 * device never sleeps while charging (WOF power-button workaround).
 */
export function SetStayAwakeWhileCharging(serial: string, enabled: boolean): $CancellablePromise<string> {
    return $Call.ByID(1573715293, serial, enabled);
}

export function SideloadPackage(serial: string, zipPath: string): $CancellablePromise<string> {
    return $Call.ByID(1263605814, serial, zipPath);
}

export function StartLogcat(serial: string, levels: string, tagFilter: string): $CancellablePromise<void> {
    return $Call.ByID(3142239049, serial, levels, tagFilter);
}

export function StartScrcpyRecording(serial: string, outputPath: string, opts: scrcpy$0.Options): $CancellablePromise<void> {
    return $Call.ByID(2124951628, serial, outputPath, opts);
}

export function StartScrcpySession(serial: string, opts: scrcpy$0.Options): $CancellablePromise<scrcpy$0.Session | null> {
    return $Call.ByID(1920301527, serial, opts);
}

export function StartTerminal(serial: string): $CancellablePromise<shell$0.Session | null> {
    return $Call.ByID(3009548683, serial);
}

export function StartTerminalSession(mode: string, serial: string, initialArgs: string): $CancellablePromise<shell$0.Session | null> {
    return $Call.ByID(2457550773, mode, serial, initialArgs);
}

export function StopLogcat(serial: string): $CancellablePromise<void> {
    return $Call.ByID(4118370667, serial);
}

export function StopScrcpyRecording(): $CancellablePromise<string> {
    return $Call.ByID(761951406);
}

export function StopScrcpySession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1560810957, sessionID);
}

export function TakeScrcpyScreenshot(sessionID: string, outputPath: string): $CancellablePromise<string> {
    return $Call.ByID(296610348, sessionID, outputPath);
}

export function UninstallMultiplePackages(packageNames: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(312649312, packageNames);
}

export function UninstallPackage(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(2909213663, packageName);
}

export function UpdatePreferences(payload: core$0.PreferencesPayload): $CancellablePromise<core$0.AppConfigSnapshot> {
    return $Call.ByID(638964798, payload);
}

export function UpdateScrcpyOptions(options: core$0.ScrcpyOptions): $CancellablePromise<void> {
    return $Call.ByID(2810162016, options);
}

/**
 * WakeAndUnlock wakes the screen and dismisses a non-secure keyguard in one
 * call (WOF one-tap turn-on for a dead power button).
 */
export function WakeAndUnlock(serial: string): $CancellablePromise<string> {
    return $Call.ByID(3881490210, serial);
}

/**
 * WakeScreen turns the device screen on via KEYCODE_WAKEUP, replacing the
 * physical power button once the device is booted.
 */
export function WakeScreen(serial: string): $CancellablePromise<string> {
    return $Call.ByID(1723300113, serial);
}

export function WipeData(serial: string): $CancellablePromise<string> {
    return $Call.ByID(3602825598, serial);
}
