// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LogcatEntry {
    "id": string;
    "serial": string;
    "date": string;
    "time": string;
    "pid": string;
    "tid": string;
    "level": string;
    "tag": string;
    "message": string;
    "raw": string;
    "timestamp": string;

    /** Creates a new LogcatEntry instance. */
    constructor($$source: Partial<LogcatEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("serial" in $$source)) {
            this["serial"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("pid" in $$source)) {
            this["pid"] = "";
        }
        if (!("tid" in $$source)) {
            this["tid"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("raw" in $$source)) {
            this["raw"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogcatEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogcatEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogcatEntry($$parsedSource as Partial<LogcatEntry>);
    }
}

export class LogcatStatusEvent {
    "serial": string;
    "status": string;

    /** Creates a new LogcatStatusEvent instance. */
    constructor($$source: Partial<LogcatStatusEvent> = {}) {
        if (!("serial" in $$source)) {
            this["serial"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogcatStatusEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): LogcatStatusEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogcatStatusEvent($$parsedSource as Partial<LogcatStatusEvent>);
    }
}

export class Session {
    "id": string;
    "serial": string;
    "mode": string;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("serial" in $$source)) {
            this["serial"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session($$parsedSource as Partial<Session>);
    }
}
