// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Details {
    "packageName": string;
    "versionName": string;
    "versionCode": string;
    "apkSizeBytes": number;
    "dataSizeBytes": number;
    "totalSizeBytes": number;

    /** Creates a new Details instance. */
    constructor($$source: Partial<Details> = {}) {
        if (!("packageName" in $$source)) {
            this["packageName"] = "";
        }
        if (!("versionName" in $$source)) {
            this["versionName"] = "";
        }
        if (!("versionCode" in $$source)) {
            this["versionCode"] = "";
        }
        if (!("apkSizeBytes" in $$source)) {
            this["apkSizeBytes"] = 0;
        }
        if (!("dataSizeBytes" in $$source)) {
            this["dataSizeBytes"] = 0;
        }
        if (!("totalSizeBytes" in $$source)) {
            this["totalSizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Details instance from a string or object.
     */
    static createFrom($$source: any = {}): Details {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Details($$parsedSource as Partial<Details>);
    }
}

export class Info {
    "packageName": string;
    "isEnabled": boolean;
    "isSystemApp": boolean;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("packageName" in $$source)) {
            this["packageName"] = "";
        }
        if (!("isEnabled" in $$source)) {
            this["isEnabled"] = false;
        }
        if (!("isSystemApp" in $$source)) {
            this["isSystemApp"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info($$parsedSource as Partial<Info>);
    }
}
