// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCustomBinary(arg1) {
  return window['go']['main']['App']['ClearCustomBinary'](arg1);
}

export function CompleteSetup() {
  return window['go']['main']['App']['CompleteSetup']();
}

export function GetBinaryStatus() {
  return window['go']['main']['App']['GetBinaryStatus']();
}

export function GetCapabilities() {
  return window['go']['main']['App']['GetCapabilities']();
}

export function GetManagedBinaryDir() {
  return window['go']['main']['App']['GetManagedBinaryDir']();
}

export function GetSetupState() {
  return window['go']['main']['App']['GetSetupState']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListManagedBinaries() {
  return window['go']['main']['App']['ListManagedBinaries']();
}

export function RetryBinaryDetection() {
  return window['go']['main']['App']['RetryBinaryDetection']();
}

export function SelectBinaryFile(arg1) {
  return window['go']['main']['App']['SelectBinaryFile'](arg1);
}

export function SelectPlatformToolsDirectory() {
  return window['go']['main']['App']['SelectPlatformToolsDirectory']();
}

export function SetCustomBinary(arg1, arg2) {
  return window['go']['main']['App']['SetCustomBinary'](arg1, arg2);
}
