// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {binary} from '../models';
import {flasher} from '../models';
import {scrcpy} from '../models';
import {core} from '../models';
import {audit} from '../models';
import {device} from '../models';
import {packagemgr} from '../models';
import {file} from '../models';
import {dialog} from '../models';
import {shell} from '../models';

export function CancelFileTransfer():Promise<void>;

export function ClearAuditLogs():Promise<void>;

export function ClearCustomBinary(arg1:string):Promise<void>;

export function ClearDeviceNickname(arg1:string):Promise<void>;

export function ClearPackageData(arg1:string):Promise<string>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CompleteSetup():Promise<binary.SetupState>;

export function ConnectWireless(arg1:string):Promise<string>;

export function CreateDirectory(arg1:string):Promise<string>;

export function DeleteFile(arg1:string):Promise<string>;

export function DeleteMultipleFiles(arg1:Array<string>):Promise<string>;

export function DisableMultiplePackages(arg1:Array<string>):Promise<string>;

export function DisablePackage(arg1:string):Promise<string>;

export function DisconnectWireless(arg1:string):Promise<string>;

export function DownloadPlatformTools():Promise<void>;

export function DownloadScrcpy():Promise<void>;

export function EnableMultiplePackages(arg1:Array<string>):Promise<string>;

export function EnablePackage(arg1:string):Promise<string>;

export function EnableWirelessTCPIP(arg1:string,arg2:string):Promise<string>;

export function ExportAuditLogs(arg1:string):Promise<void>;

export function FastbootContinue(arg1:string):Promise<string>;

export function FlashPartition(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FlashRomFolder(arg1:string,arg2:string,arg3:flasher.Plan):Promise<string>;

export function ForceStopPackage(arg1:string):Promise<string>;

export function GetActiveScrcpySession():Promise<scrcpy.Session>;

export function GetActiveSerial():Promise<string>;

export function GetActiveSlot(arg1:string):Promise<string>;

export function GetAppConfig():Promise<core.AppConfigSnapshot>;

export function GetAuditLogs(arg1:number):Promise<Array<audit.Entry>>;

export function GetBinaryStatus():Promise<binary.BinarySetupResult>;

export function GetCapabilities():Promise<Record<string, boolean>>;

export function GetDeviceInfo(arg1:string):Promise<device.Info>;

export function GetDeviceMode(arg1:string):Promise<device.Mode>;

export function GetDeviceNicknames():Promise<Record<string, string>>;

export function GetDevices():Promise<Array<device.Summary>>;

export function GetDirectorySize(arg1:string):Promise<string>;

export function GetFastbootDevices():Promise<Array<flasher.FastbootDeviceInfo>>;

export function GetManagedBinaryDir():Promise<string>;

export function GetPackageDetails(arg1:string):Promise<packagemgr.Details>;

export function GetPerformanceSnapshot(arg1:string):Promise<device.PerformanceSnapshot>;

export function GetRuntimeDiagnostics():Promise<core.RuntimeDiagnostics>;

export function GetScrcpyClipboard(arg1:string):Promise<string>;

export function GetScrcpyEncoderSupport(arg1:string):Promise<scrcpy.EncoderSupport>;

export function GetSetupState():Promise<binary.SetupState>;

export function GetStayAwakeWhileCharging(arg1:string):Promise<boolean>;

export function GetStorageInfo():Promise<file.StorageInfo>;

export function ImportAuditLogs(arg1:string):Promise<number>;

export function InstallPackage(arg1:string):Promise<string>;

export function IsUserspaceFastboot(arg1:string):Promise<boolean>;

export function LaunchPackage(arg1:string):Promise<string>;

export function ListFiles(arg1:string,arg2:boolean):Promise<Array<file.Entry>>;

export function ListManagedBinaries():Promise<Array<string>>;

export function ListPackages(arg1:string):Promise<Array<packagemgr.Info>>;

export function PullFile(arg1:string,arg2:string):Promise<string>;

export function PullMultipleFiles(arg1:Array<string>,arg2:string):Promise<string>;

export function PullPackageApk(arg1:string):Promise<string>;

export function PushFile(arg1:string,arg2:string):Promise<string>;

export function PushMultipleFiles(arg1:Array<string>,arg2:string):Promise<string>;

export function PushScrcpyClipboard(arg1:string,arg2:string):Promise<void>;

export function RebootDevice(arg1:string,arg2:string):Promise<string>;

export function RenameFile(arg1:string,arg2:string):Promise<string>;

export function RetryBinaryDetection():Promise<binary.BinarySetupResult>;

export function RunCustomFastbootCommand(arg1:string,arg2:string):Promise<string>;

export function SaveLogcatToFile(arg1:string,arg2:string):Promise<void>;

export function ScanRomFolder(arg1:string):Promise<flasher.Plan>;

export function SelectApkFile():Promise<string>;

export function SelectBinaryFile(arg1:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectFlashImageFile():Promise<string>;

export function SelectMultipleFiles():Promise<Array<string>>;

export function SelectPlatformToolsDirectory():Promise<dialog.PlatformToolsSelection>;

export function SelectSavePath(arg1:string):Promise<string>;

export function SelectSideloadFile():Promise<string>;

export function SendTerminalInput(arg1:string,arg2:string):Promise<void>;

export function SetActiveSerial(arg1:string):Promise<void>;

export function SetActiveSlot(arg1:string,arg2:string):Promise<string>;

export function SetCustomBinary(arg1:string,arg2:string):Promise<void>;

export function SetDeviceNickname(arg1:string,arg2:string):Promise<void>;

export function SetStayAwakeWhileCharging(arg1:string,arg2:boolean):Promise<string>;

export function SideloadPackage(arg1:string,arg2:string):Promise<string>;

export function StartLogcat(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartScrcpyRecording(arg1:string,arg2:string,arg3:scrcpy.Options):Promise<void>;

export function StartScrcpySession(arg1:string,arg2:scrcpy.Options):Promise<scrcpy.Session>;

export function StartTerminal(arg1:string):Promise<shell.Session>;

export function StartTerminalSession(arg1:string,arg2:string,arg3:string):Promise<shell.Session>;

export function StopLogcat(arg1:string):Promise<void>;

export function StopScrcpyRecording():Promise<string>;

export function StopScrcpySession(arg1:string):Promise<void>;

export function TakeScrcpyScreenshot(arg1:string,arg2:string):Promise<string>;

export function UninstallMultiplePackages(arg1:Array<string>):Promise<string>;

export function UninstallPackage(arg1:string):Promise<string>;

export function UpdatePreferences(arg1:core.PreferencesPayload):Promise<core.AppConfigSnapshot>;

export function UpdateScrcpyOptions(arg1:core.ScrcpyOptions):Promise<void>;

export function WakeAndUnlock(arg1:string):Promise<string>;

export function WakeScreen(arg1:string):Promise<string>;

export function WipeData(arg1:string):Promise<string>;
