// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearCustomBinary(arg1:string):Promise<void>;

export function CompleteSetup():Promise<main.SetupState>;

export function GetBinaryStatus():Promise<main.BinarySetupResult>;

export function GetCapabilities():Promise<Record<string, boolean>>;

export function GetManagedBinaryDir():Promise<string>;

export function GetSetupState():Promise<main.SetupState>;

export function Greet(arg1:string):Promise<string>;

export function ListManagedBinaries():Promise<Array<string>>;

export function RetryBinaryDetection():Promise<main.BinarySetupResult>;

export function SelectBinaryFile(arg1:string):Promise<string>;

export function SelectPlatformToolsDirectory():Promise<main.PlatformToolsSelection>;

export function SetCustomBinary(arg1:string,arg2:string):Promise<void>;
