// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCustomBinary(arg1) {
  return window['go']['main']['App']['ClearCustomBinary'](arg1);
}

export function ClearDeviceNickname(arg1) {
  return window['go']['main']['App']['ClearDeviceNickname'](arg1);
}

export function ClearPackageData(arg1) {
  return window['go']['main']['App']['ClearPackageData'](arg1);
}

export function CompleteSetup() {
  return window['go']['main']['App']['CompleteSetup']();
}

export function ConnectWireless(arg1) {
  return window['go']['main']['App']['ConnectWireless'](arg1);
}

export function DisableMultiplePackages(arg1) {
  return window['go']['main']['App']['DisableMultiplePackages'](arg1);
}

export function DisablePackage(arg1) {
  return window['go']['main']['App']['DisablePackage'](arg1);
}

export function DisconnectWireless(arg1) {
  return window['go']['main']['App']['DisconnectWireless'](arg1);
}

export function EnableMultiplePackages(arg1) {
  return window['go']['main']['App']['EnableMultiplePackages'](arg1);
}

export function EnablePackage(arg1) {
  return window['go']['main']['App']['EnablePackage'](arg1);
}

export function EnableWirelessTCPIP(arg1, arg2) {
  return window['go']['main']['App']['EnableWirelessTCPIP'](arg1, arg2);
}

export function ForceStopPackage(arg1) {
  return window['go']['main']['App']['ForceStopPackage'](arg1);
}

export function GetActiveSerial() {
  return window['go']['main']['App']['GetActiveSerial']();
}

export function GetBinaryStatus() {
  return window['go']['main']['App']['GetBinaryStatus']();
}

export function GetCapabilities() {
  return window['go']['main']['App']['GetCapabilities']();
}

export function GetDeviceInfo(arg1) {
  return window['go']['main']['App']['GetDeviceInfo'](arg1);
}

export function GetDeviceMode(arg1) {
  return window['go']['main']['App']['GetDeviceMode'](arg1);
}

export function GetDeviceNicknames() {
  return window['go']['main']['App']['GetDeviceNicknames']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetManagedBinaryDir() {
  return window['go']['main']['App']['GetManagedBinaryDir']();
}

export function GetPackageDetails(arg1) {
  return window['go']['main']['App']['GetPackageDetails'](arg1);
}

export function GetPerformanceSnapshot(arg1) {
  return window['go']['main']['App']['GetPerformanceSnapshot'](arg1);
}

export function GetSetupState() {
  return window['go']['main']['App']['GetSetupState']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallPackage(arg1) {
  return window['go']['main']['App']['InstallPackage'](arg1);
}

export function LaunchPackage(arg1) {
  return window['go']['main']['App']['LaunchPackage'](arg1);
}

export function ListManagedBinaries() {
  return window['go']['main']['App']['ListManagedBinaries']();
}

export function ListPackages(arg1) {
  return window['go']['main']['App']['ListPackages'](arg1);
}

export function PullPackageApk(arg1) {
  return window['go']['main']['App']['PullPackageApk'](arg1);
}

export function RebootDevice(arg1, arg2) {
  return window['go']['main']['App']['RebootDevice'](arg1, arg2);
}

export function RetryBinaryDetection() {
  return window['go']['main']['App']['RetryBinaryDetection']();
}

export function SelectApkFile() {
  return window['go']['main']['App']['SelectApkFile']();
}

export function SelectBinaryFile(arg1) {
  return window['go']['main']['App']['SelectBinaryFile'](arg1);
}

export function SelectPlatformToolsDirectory() {
  return window['go']['main']['App']['SelectPlatformToolsDirectory']();
}

export function SetActiveSerial(arg1) {
  return window['go']['main']['App']['SetActiveSerial'](arg1);
}

export function SetCustomBinary(arg1, arg2) {
  return window['go']['main']['App']['SetCustomBinary'](arg1, arg2);
}

export function SetDeviceNickname(arg1, arg2) {
  return window['go']['main']['App']['SetDeviceNickname'](arg1, arg2);
}

export function UninstallMultiplePackages(arg1) {
  return window['go']['main']['App']['UninstallMultiplePackages'](arg1);
}

export function UninstallPackage(arg1) {
  return window['go']['main']['App']['UninstallPackage'](arg1);
}
