// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearCustomBinary(arg1:string):Promise<void>;

export function ClearDeviceNickname(arg1:string):Promise<void>;

export function ClearPackageData(arg1:string):Promise<string>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CompleteSetup():Promise<main.SetupState>;

export function ConnectWireless(arg1:string):Promise<string>;

export function CreateDirectory(arg1:string):Promise<string>;

export function DeleteFile(arg1:string):Promise<string>;

export function DeleteMultipleFiles(arg1:Array<string>):Promise<string>;

export function DisableMultiplePackages(arg1:Array<string>):Promise<string>;

export function DisablePackage(arg1:string):Promise<string>;

export function DisconnectWireless(arg1:string):Promise<string>;

export function EnableMultiplePackages(arg1:Array<string>):Promise<string>;

export function EnablePackage(arg1:string):Promise<string>;

export function EnableWirelessTCPIP(arg1:string,arg2:string):Promise<string>;

export function FlashPartition(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FlashRomFolder(arg1:string,arg2:string,arg3:main.FlashPlan):Promise<string>;

export function ForceStopPackage(arg1:string):Promise<string>;

export function GetActiveSerial():Promise<string>;

export function GetActiveSlot(arg1:string):Promise<string>;

export function GetBinaryStatus():Promise<main.BinarySetupResult>;

export function GetCapabilities():Promise<Record<string, boolean>>;

export function GetDeviceInfo(arg1:string):Promise<main.DeviceInfo>;

export function GetDeviceMode(arg1:string):Promise<main.DeviceMode>;

export function GetDeviceNicknames():Promise<Record<string, string>>;

export function GetDevices():Promise<Array<main.DeviceSummary>>;

export function GetDirectorySize(arg1:string):Promise<string>;

export function GetFastbootDevices():Promise<Array<main.FastbootDeviceInfo>>;

export function GetManagedBinaryDir():Promise<string>;

export function GetPackageDetails(arg1:string):Promise<main.PackageDetails>;

export function GetPerformanceSnapshot(arg1:string):Promise<main.PerformanceSnapshot>;

export function GetSetupState():Promise<main.SetupState>;

export function GetStorageInfo():Promise<main.StorageInfo>;

export function Greet(arg1:string):Promise<string>;

export function InstallPackage(arg1:string):Promise<string>;

export function IsUserspaceFastboot(arg1:string):Promise<boolean>;

export function LaunchPackage(arg1:string):Promise<string>;

export function ListFiles(arg1:string,arg2:boolean):Promise<Array<main.FileEntry>>;

export function ListManagedBinaries():Promise<Array<string>>;

export function ListPackages(arg1:string):Promise<Array<main.PackageInfo>>;

export function PullFile(arg1:string,arg2:string):Promise<string>;

export function PullMultipleFiles(arg1:Array<string>,arg2:string):Promise<string>;

export function PullPackageApk(arg1:string):Promise<string>;

export function PushFile(arg1:string,arg2:string):Promise<string>;

export function PushMultipleFiles(arg1:Array<string>,arg2:string):Promise<string>;

export function RebootDevice(arg1:string,arg2:string):Promise<string>;

export function RenameFile(arg1:string,arg2:string):Promise<string>;

export function RetryBinaryDetection():Promise<main.BinarySetupResult>;

export function RunCustomFastbootCommand(arg1:string,arg2:string):Promise<string>;

export function SaveLogcatToFile(arg1:string,arg2:string):Promise<void>;

export function ScanRomFolder(arg1:string):Promise<main.FlashPlan>;

export function SelectApkFile():Promise<string>;

export function SelectBinaryFile(arg1:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectFlashImageFile():Promise<string>;

export function SelectMultipleFiles():Promise<Array<string>>;

export function SelectPlatformToolsDirectory():Promise<main.PlatformToolsSelection>;

export function SelectSideloadFile():Promise<string>;

export function SendTerminalInput(arg1:string,arg2:string):Promise<void>;

export function SetActiveSerial(arg1:string):Promise<void>;

export function SetActiveSlot(arg1:string,arg2:string):Promise<string>;

export function SetCustomBinary(arg1:string,arg2:string):Promise<void>;

export function SetDeviceNickname(arg1:string,arg2:string):Promise<void>;

export function SideloadPackage(arg1:string,arg2:string):Promise<string>;

export function StartLogcat(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartTerminal(arg1:string):Promise<main.TerminalSession>;

export function StartTerminalSession(arg1:string,arg2:string,arg3:string):Promise<main.TerminalSession>;

export function StopLogcat(arg1:string):Promise<void>;

export function UninstallMultiplePackages(arg1:Array<string>):Promise<string>;

export function UninstallPackage(arg1:string):Promise<string>;

export function WipeData(arg1:string):Promise<string>;
